name: Feature request
about: Propose a new capability or enhancement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What do you want Agently-Go to provide?
    validations:
      required: true

  - type: textarea
    id: parity
    attributes:
      label: Python parity reference (optional)
      description: If this is parity-related, include Python source/tests/examples paths.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered

  - type: textarea
    id: extra
    attributes:
      label: Additional context
